[package]
name = "wifi-capture"
version = "0.1.0"
edition = "2024"

[dependencies]
ctrlc = "3.4.6"
libwifi = "0.4.6"
pcap = "2.2.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

